name: Server Staging Deploy

on:
  push:
    branches:
      - staging

jobs:
  build-and-deploy-staging:
    runs-on: ubuntu-latest

    env:
      DOCKER_REGISTRY: registry.digitalocean.com
      IMAGE_NAME: mosh-do-docker-reg/mailmate-server-staging
      IMAGE_TAG: staging

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to DigitalOcean Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCR_USERNAME }}
          password: ${{ secrets.DO_API_TOKEN }}

      - name: Build Docker image
        working-directory: server
        run: |
          docker build \
            -f Dockerfile \
            -t $DOCKER_REGISTRY/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
            .

      - name: Push Docker image
        working-directory: server
        run: |
          docker push $DOCKER_REGISTRY/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Install doctl
        run: |
          sudo snap install doctl --classic
          doctl auth init -t ${{ secrets.DO_API_TOKEN }}

      - name: Deploy to DigitalOcean App Platform (Staging)
        run: |
          doctl apps update ${{ secrets.APP_ID_STG }} \
            --spec .do/server-app-staging.yaml