name: Server - Production Deploy

on:
  push:
    branches:
      - production

jobs:
  build-and-deploy-prod:
    runs-on: ubuntu-latest

    env:
      DOCKER_REGISTRY: registry.digitalocean.com
      IMAGE_NAME: mosh-do-docker-reg/mailmate-server
      IMAGE_TAG: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to DigitalOcean Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCR_USERNAME }}
          password: ${{ secrets.DO_API_TOKEN }}

      - name: Build Docker image
        working-directory: server
        run: |
          docker build \
            -f Dockerfile \
            -t $DOCKER_REGISTRY/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
            .

      - name: Push Docker image
        working-directory: server
        run: |
          docker push $DOCKER_REGISTRY/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}